replicaCount: 1

image:
  repository: ""   # required
  tag: ""          # required
  pullPolicy: IfNotPresent

securityContext: {}

containerSecurityContext: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}

probes:
  liveness: {}
  readiness: {}
  startup: {}

env: []
envFrom: []

volumes: []
volumeMounts: []
